name: stocks
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - pymongo
  - numpy
  - pandas
  - scikit-learn
  - nltk # also need data in env using nltk.download()
  - gensim
  - spacy
  - spacy-model-en_core_web_sm
